language: php
php:
- 7.0
- 7.1
- 7.2
install: composer install
notifications:
  email: false
  slack:
    secure: Pm7F6BT/DM38i8bqTWDx/LlDY5zJ7NqTDVtNS0R4ipJGxfs3hxLwqPXHIOEbq66ELDhy4g3YEoN7pZMND3AkhJu2rF/ScKkgx9j745q4qXiybhOjWumTul+99Lw17Lj1FFkSj3ixyfxV7Xd8UXPvxxWZz0FJVIt5lPm1BCDdD99pI64ZK/MbFzOb/oJcokf9JqDgvZsz6yh3BxytN5ZQ/1UzUozh/YhDmTtjch1mePKKco7exY0MPQ4wxhleNbplshlW9rBgVCE2G3K68CP+6i1RPDZYzo+buGMRUoYxYAZIXwHcCsrGz1fG3hWUgn9xwmzQD+v4e1HWD0/3yqhxt9lUZjKtVhUUUUVawjMOnlvMgnEF2Hb6X5OmENxScVtSAgz8aXJf/vXFWes6RYY3EHAqs9j6Rr098b1NQaAEtyH+vOXDBBXr+4AXlmunvcUxiKcgBAWgjOXBNiQunVDS7KkaFdOdKOZPlAYOKxh1irm8WJpU0nyPep0xwCGuLI8rVOZ+cnqS+aKczQi1PUalRO1aFil6tq0LTlMgybYrB5ICgB3eCyY81L8ez7uC2g4Ymrv/SR+xrOkZvndzGfj/AkTb624g91tRx1gTEv9mRPaCo8+wQKTpwUugggHEeg/gXRET1ZxO8VqQhGFvQs5jTUCZNqhiL59mVV+eY8hXwpk=
